// Rebuilds tests/unit/tokenizer_llamacpp.json: token ids from llama.cpp's llama-tokenize (the
// reference) for a corpus of tricky prompts, on the vocab-only GGUFs llama.cpp ships in models/.
// CPU only. The fixture keeps just the vocab entries and merges these prompts use (ranks in their
// original order), which gives the same BPE result and keeps the file small.
//
//   deno run --allow-read --allow-write --allow-run --allow-env scripts/tokenizer-fixture.js \
//     [--llama-tokenize PATH] [--models ~/llama.cpp/models]
import { makeTokenizer, preSplitter } from "../engine/tokenizer.js";
import { parseGGUFHeader, tokenizerFromGGUF } from "../engine/gguf.js";

export const CORPUS = [
  "Hello world",
  "Hello  world\n\n  x = 12345;",
  "def f(x):\n    return x**2 + 3.14159\n\n\nprint(f(10))",
  "function add(a, b) {\n\treturn a + b; // sum\n}\n",
  "const s = `${name}!`;\r\nif (a !== b) { throw new Error(\"bad\"); }",
  "    indented\n        more\n\t\ttabs\n  \n",
  "trailing spaces   \nand   \n\n\n",
  "I'm sure they'll say it's fine, we've done it, I'd go. DON'T WON'T I'M",
  "numbers: 1234567890, 3.14, -42, 1e10, 0x1F, 1,000,000",
  "年份2024年，价格￥1999元。你好，世界！",
  "日本語のテキストです。カタカナとひらがな、漢字。",
  "한국어 텍스트 입니다. 안녕하세요!",
  "Привет, мир! Как дела? Ёлка",
  "مرحبا بالعالم ١٢٣٤",
  "हिन्दी पाठ, नमस्ते दुनिया ५६७",
  "ภาษาไทย สวัสดีครับ",
  "emoji 😀😃😄 👍🏽 👨‍👩‍👧‍👦 🇺🇸 ❤️ ✨🚀",
  "café naïve résumé  é ñ",
  "a b c　d​e",
  "mixed: abc123def 12ab ab12 x1y2z3",
  "((foo)) [bar] {baz} <qux> ...ellipsis --- ===",
  "path/to/file.js:12:5 https://example.com/a?b=c&d=e#f",
  "<div class=\"x\">Hi</div>\n<!-- comment -->",
  "SELECT * FROM users WHERE id = 42;\n-- sql comment",
  "  leading spaces",
  "\n\nleading newlines",
  "\r\n\r\nwindows\r\nlines\r\n",
  "a\n b\n  c\n   d",
  "tab\tseparated\tvalues\t\t\n",
  "½ ¾ ² ³ Ⅻ ① ٣",
  "'s 'S 'Re 've 'LL 'd 'x",
  "x = y.map(v => v * 2).filter(Boolean);",
  "#include <stdio.h>\nint main(){printf(\"%d\\n\", 1+1);}",
  "𝔘𝔫𝔦𝔠𝔬𝔡𝔢 𝐛𝐨𝐥𝐝 𠀀𠀁 CJK ext B",
  "$$E = mc^2$$ and \\frac{a}{b}",
  "   ",
  "\n",
  "!!!???...",
  "Tabby ids · fn(x) => 1024 ✓",
  // Unicode White_Space vs JS \s: U+0085 is space, U+FEFF is not
  "x \u0085y 1\u00852 \ufeff!BOM \ufeff\ufeffz",
  "line\u2028sep\u2029para\u00a0nbsp\u3000ideo\u202f!\u205f\n",
];
// qwen2 = Qwen 2/2.5/3, qwen35 = Qwen 3.5+, starcoder = the Digits split SmolLM uses, gpt-2 = default
const VOCABS = ["qwen2", "qwen35", "starcoder", "gpt-2"];

// the tokenizer's byte -> char table (GPT-2 bytes_to_unicode)
function byteChars() {
  const bs = [];
  for (let i = 33; i <= 126; i++) bs.push(i);
  for (let i = 161; i <= 172; i++) bs.push(i);
  for (let i = 174; i <= 255; i++) bs.push(i);
  const cs = bs.slice();
  let n = 0;
  for (let b = 0; b < 256; b++) if (!bs.includes(b)) { bs.push(b); cs.push(256 + n); n++; }
  const out = [];
  bs.forEach((b, i) => { out[b] = String.fromCharCode(cs[i]); });
  return out;
}

// the plain BPE loop, noting every merge it applies and every symbol it makes
function bpeUsed(word, ranks, usedMerges, usedToks) {
  let parts = [...word];
  for (const p of parts) usedToks.add(p);
  while (parts.length > 1) {
    let best = null, bestRank = Infinity;
    for (let i = 0; i < parts.length - 1; i++) {
      const r = ranks.get(parts[i] + " " + parts[i + 1]);
      if (r !== undefined && r < bestRank) { bestRank = r; best = i; }
    }
    if (best === null) break;
    usedMerges.add(bestRank);
    usedToks.add(parts[best] + parts[best + 1]);
    parts = [...parts.slice(0, best), parts[best] + parts[best + 1], ...parts.slice(best + 2)];
  }
}

async function llamaTokenize(bin, gguf, text) {
  const f = await Deno.makeTempFile();
  try {
    await Deno.writeTextFile(f, text);
    const env = { CUDA_VISIBLE_DEVICES: "", LD_LIBRARY_PATH: bin.replace(/\/[^/]*$/, "") };
    const args = ["-m", gguf, "-bf", f, "--ids", "--log-disable", "--no-parse-special", "--no-bos", "--no-escape"];
    const out = await new Deno.Command(bin, { args, env, stderr: "null" }).output();
    if (!out.success) throw new Error("llama-tokenize failed on " + JSON.stringify(text));
    return JSON.parse(new TextDecoder().decode(out.stdout).trim().split("\n").pop());
  } finally { await Deno.remove(f); }
}

if (import.meta.main) {
  const arg = (k, d) => { const i = Deno.args.indexOf(k); return i >= 0 ? Deno.args[i + 1] : d; };
  const home = Deno.env.get("HOME");
  const bin = arg("--llama-tokenize", `${home}/llm/llama-unsloth/llama-tokenize`);
  const models = arg("--models", `${home}/llama.cpp/models`);
  const chars = byteChars(), enc = new TextEncoder();
  const fixture = { note: "generated by scripts/tokenizer-fixture.js; ids are llama.cpp's", corpus: CORPUS, vocabs: {} };
  for (const v of VOCABS) {
    const gguf = `${models}/ggml-vocab-${v}.gguf`;
    const tj = tokenizerFromGGUF(parseGGUFHeader(Deno.readFileSync(gguf).buffer).meta);
    const ranks = new Map(tj.model.merges.map((m, i) => [m, i]));
    const usedMerges = new Set(), usedToks = new Set(), ids = [];
    const split = preSplitter(tj), tok = makeTokenizer(tj);
    let bad = 0;
    for (const text of CORPUS) {
      const ref = await llamaTokenize(bin, gguf, text);
      ids.push(ref);
      for (const piece of split(text)) bpeUsed([...enc.encode(piece)].map((b) => chars[b]).join(""), ranks, usedMerges, usedToks);
      if (tok.encode(text).join() !== ref.join()) { bad++; console.error(`${v}: mismatch on ${JSON.stringify(text)}`); }
    }
    const vocab = {};
    for (const t of usedToks) vocab[t] = tj.model.vocab[t];
    const merges = [...usedMerges].sort((a, b) => a - b).map((r) => tj.model.merges[r]);
    fixture.vocabs[v] = { pre: tj.pre, vocab, merges, ids };
    console.log(`${v}: ${CORPUS.length - bad}/${CORPUS.length} match, ${usedToks.size} tokens, ${merges.length} merges`);
  }
  const out = new URL("../tests/unit/tokenizer_llamacpp.json", import.meta.url);
  Deno.writeTextFileSync(out, JSON.stringify(fixture) + "\n");
}
